### ISSUE TITLE
 I would like to adopt the plugin

### ISSUE THREAD

**Issue by Dudo1985** [Dudo1985/Comments-Not-Replied-To#30]
Hello guys, I’ve found the adopt-me tag.

I would like to adopt this plugin.

Would you like to[ transfer ownership to me?](https://developer.wordpress.org/plugins/wordpress-org/plugin-developer-faq/#plugin-ownership)

Let me know!

Best,
Dario

**Comment by tommcfarlin** [comment]
I'm happy to transfer ownership of this to you; however, there are other developers involved that I'd like them to sign off on, too. @norcross @pippinsplugins

**Comment by pippinsplugins** [comment]
No objection from me!

**Comment by pippinsplugins** [comment]
Norcross gave his approval via email so I've gone ahead and transferred ownership of the repo over to you @Dudo1985.

Thanks for your interest and keeping the plugin alive!

**Comment by Dudo1985** [comment]
Thank you!
